### ISSUE TITLE
Hangs on a Model2 V V1.1

### ISSUE THREAD

**Issue by nophead** [srcshelton/servoblaster#2]
I initially tried @richardghirst's version but it came up with Board model 1 and did nothing.

Trying this version I get the following:
```
Board model:                     2
GPIO configuration:             P1 (40 pins)
Using hardware:                PWM
Using DMA channel:              14
Idle timeout:             Disabled
Number of servos:                8
Servo cycle time:            20000us
Pulse increment step size:      10us
Minimum width value:            50 (500us)
Maximum width value:           250 (2500us)
Output levels:              Normal

Using P1 pins:                    7,11,12,13,15,16,18,22

Servo mapping:
     0 on P1-7               GPIO-4
     1 on P1-11              GPIO-17
     2 on P1-12              GPIO-18
     3 on P1-13              GPIO-27
     4 on P1-15              GPIO-22
     5 on P1-16              GPIO-23
     6 on P1-18              GPIO-24
     7 on P1-22              GPIO-25
```

But it doesn't return to the command prompt.

The early B2 is a different SOC from the later ones. Is is expected to work?

**Comment by archy587** [comment]
I had the same issue with the hanging command prompt. I used:

sudo nohup ./servod  &

to run without hangup and ignore output...then normal control worked...

**Comment by srcshelton** [comment]
This version of `servoblaster` doesn't run in the background by default - if you want it to do that, add `--daemonise=1` as a command-line argument.  This is to make running `servod` as a service easier (and to make it more convenient to debug).

(Apologies for the delay in replying, by the way!)
