### ISSUE TITLE
servod status inconsistent

### ISSUE THREAD

**Issue by srcshelton** [srcshelton/servoblaster#5]
On Saturday 3 March at 05:40, @hkeown said:

> Hi Stuart,
> 
> Just a comment, there seems to be inconsistency when servod is configured and the actual status of servod. As in my case, I’m using pins 11 and 12, but servod doesn’t shows this in its configuration.
> 
> Also, I might have missed this, but it appears that servod is configured for 8 servos, I’m only using 2. Where do I configure the number of servos?
> 
> Best regards,
> 
> Harvey

**Comment by srcshelton** [comment]
Hi Harvey,

Could you post the command-line options or configuration file used to start `servod`, and also the inaccurate status output produced as a result?

The intended behaviour is for all servos to be active if nothing has been specifically configured, but to only use the specified servos if a set pins is provided.

(P.S. Please try to open different problems in different Issues!)

Cheers,

Stuart

**Comment by hkeown** [comment]
Hi Stuart,

Apologies for the delay, I had a PhD deliverable that absorbed all of my spare time...

I trust that the information below is what you're requesting.

Best regards,
Harvey

```
---------------------------------------------------------------
sudo nano /etc/init.d/servoblaster
#H.Keown 27/02/2018 - Use GPIO17,18, eliminate jitter
OPTS="--idle-timeout=2000 --p1pins=11,12 --max=235"

---------------------------------------------------------------
# Simple test to see if the device file was created
def servo_setup():
    global device_file

    device_file = "/dev/servoblaster"

    try:
       os.path.isfile(device_file)  # True/False: check if this is a directory
#        subprocess.run("sudo /home/pi/scripts/c/servoblaster/servod --p1pins=11,12 --max=235")  # Servo 0 = 11, Servo 1 = 12
    except:
        print("The Servo Device folder %s has NOT been created, the driver is probably not loaded" % device_file)
        raise
    else:
        print("The Device folder %s has been created" % device_file)
    finally:
        print("Exiting servo_setup()")

----------------------------------------------------------------
# Simple script to step the servos
           servoblaster_cmd = "sudo echo 0={}% > /dev/servoblaster".format(i)
            subprocess.run(servoblaster_cmd)
            print(servoblaster_cmd)
            subprocess.run = "sudo echo 1={}% > /dev/servoblaster".format(i)
            subprocess.run(servoblaster_cmd)
            print(servoblaster_cmd)

            if i == 100:
                i = 0
            else:
                i += 1

-------------------------------------------------------------------------------------------
```

![capture](https://user-images.githubusercontent.com/20144501/37275561-3fc677bc-25e8-11e8-9c41-14afd312526e.JPG)

Just a comment, there seems to be inconsistency when servod is configured and the actual status of servod. As in my case, I’m using pins 11 and 12, but servod doesn’t shows this in its configuration.

Also, I might have missed this, but it appears that servod is configured for 8 servos, I’m only using 2. Where do I configure the number of servos?_

**Comment by srcshelton** [comment]
(... several years pass - sorry!)

It's worth noting that `/dev/serovblaster` should be a named-pipe (sometimes called a `FIFO`), rather than a directory - so perhaps simply use `os.path.exists`?  Also, you may want to add a delay so that `servoblaster` has time to start before checking for it's pipe.

When `servod` starts, it outputs the settings it is running with... but won't necessarily notice that another instance is running and report the settings of the running instance.  So what you're seeing above is that the running daemon (PID 349) is using 2 servos on pins 11 and 12, but if you run `servod` manually then it outputs (and tries to run with) its hard-coded defaults.

For example, if I run:
```
$ sudo service servoblaster stop ; sudo /usr/local/sbin/servod --idle-timeout=1000 --p1pins=15,16,18,22 -s 5 -m 102 -x 444

Board model:                    3B
GPIO configuration:             P1 (40 pins)
Using hardware:                PWM
Using DMA channel:              14
Idle timeout:                 1000ms
Number of servos:                4
Servo cycle time:            20000us
Pulse increment step size:       5us
Minimum width value:           102 (510us)
Maximum width value:           444 (2220us)
Output levels:              Normal

Using P1 pins:                    15,16,18,22

Servo mapping:
     0 on P1-15              GPIO-22
     1 on P1-16              GPIO-23
     2 on P1-18              GPIO-24
     3 on P1-22              GPIO-25
```

... and you can see that here that my four servos are indeed those reported.

And to answer your final question, the number of servos is determined by the number of pins specified (using either or both of `--p1pins` and `--p5pins`) !
