### ISSUE TITLE
On Tinker Board?

### ISSUE THREAD

**Issue by Supaii** [srcshelton/servoblaster#7]
Hello,

Sorry for my English.

Will there be an extention on the ASUS Tinker Board?

**Comment by srcshelton** [comment]
I'm afraid that I didn't write the servoblaster code, I merely repackaged it and applied a patch or two... and I don't have access to Tinker Board hardware.

However, it's unlikely that the `mailbox` code is portable to other ARM platforms as it's inextricably linked to Broadcom's VideoCore GPU, so for non-Broadcom platforms a complete re-write would likely be in order.
