### ISSUE TITLE
make -  undefined reference to `makedev'

### ISSUE THREAD

**Issue by pallago** [srcshelton/servoblaster#8]
Trying to install (make) the servoblaster, the following message appeared:

`pi@raspberrypi:~/servoblaster $ sudo make install
cc -I/opt/vc/include -Wall -Wextra -g -O2 -o servod servod.c mailbox.c -L/opt/vc/lib -lm -lbcm_host
mailbox.c: In function ‘mbox_open’:
mailbox.c:281:38: warning: implicit declaration of function ‘makedev’ [-Wimplicit-function-declaration]
    if (mknod(filename, S_IFCHR|0600, makedev(100, 0)) < 0) {
                                      ^~~~~~~
/usr/bin/ld: /tmp/ccDJbBf0.o: in function `mbox_open':
/home/pi/servoblaster/mailbox.c:281: undefined reference to `makedev'
collect2: error: ld returned 1 exit status
make: *** [Makefile:12: servod] Error 1`

This error can be solved by adding the line `#include <sys/sysmacros.h>` into the **mailbox.c** file.

**Comment by srcshelton** [comment]
Thanks - I've just applied a patch from upstream which adds this include, but commit 2187f32 also refactors this code so that `makedev` is no longer needed!
